# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end_time')),
                ('operating_hours', models.TimeField(verbose_name='operating_hours')),
                ('starts', models.IntegerField(verbose_name='starts')),
                ('voltage_1', models.IntegerField(verbose_name='voltage_1')),
                ('voltage_2', models.IntegerField(verbose_name='voltage_2')),
                ('voltage_3', models.IntegerField(verbose_name='voltage_3')),
                ('tank', models.FloatField(verbose_name='tank')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'checks',
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
