# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_operating_hours_to_duration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='observation',
        ),
        migrations.AddField(
            model_name='check',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='observations'),
        ),
    ]
