# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_field_tank_to_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='tank',
            field=models.TextField(verbose_name='tank'),
        ),
    ]
