# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_field_tank_on_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='check',
            name='start_time',
            field=models.TimeField(default=b'11:39', verbose_name='start_time'),
        ),
    ]
