# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_model_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='next_service_date',
            field=models.DateField(null=True, verbose_name='next_service_date'),
        ),
        migrations.AddField(
            model_name='service',
            name='next_service_hours',
            field=models.IntegerField(null=True, verbose_name='next_service_hours'),
        ),
    ]
