# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_fields_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fuel',
            field=models.BooleanField(default=False, verbose_name='fuel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='battery',
            field=models.BooleanField(default=False, verbose_name='battery'),
        ),
    ]
