# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_field_fuel_to_service'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE checks ALTER COLUMN tank TYPE decimal(38,3);',
        'ALTER TABLE checks ALTER COLUMN tank TYPE double precision')
    ]
