# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_field_tank_from_float_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='tank',
            field=models.DecimalField(decimal_places=3, max_digits=38, verbose_name='tank'),
        ),
    ]
