"""
Django settings for armatus project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
#import environ
import ldap
from django.utils.translation import ugettext_lazy as _
from django.conf.locale.es import formats as es_formats
    
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#env = environ.Env(
    # set casting, default value
#    DEBUG=(bool, False)
#)
#environ.Env.read_env()

BASE_URL = os.environ.get('BASE_URL')
APPLICATION_NAME= os.environ.get('APPLICATION_NAME')
APPLICATION_DESC= os.environ.get('APPLICATION_DESC')

es_formats.DATETIME_FORMAT = "d-m-Y H:i"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS')

ADMINS=os.environ.get('ADMINS')

MANAGERS= os.environ.get('MANAGERS')

# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'jquery_ui',
    'bootstrap_ui',
    'django_extensions',
    'bootstrap_themes',
    'app',
    'datetimewidget',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'app.middleware.ForceLangMiddleware',
]

ROOT_URLCONF = 'armatus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'armatus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#DATABASES = { 'default': os.environ.get('DB_DEFAULT'), 'db_owner': os.environ.get("DB_OWNER") }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD':  os.environ.get('DB_USER_PASSWORD'),
        'PORT': os.environ.get('DB_PORT'),
        'HOST': os.environ.get('DB_HOST'),
    },
    'db_owner': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_OWNER'),
        'PASSWORD': os.environ.get('DB_OWNER_PASSWORD'),
        'PORT': os.environ.get('DB_PORT'),
        'HOST': os.environ.get('DB_HOST'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'es'

LANGUAGES = (
  ('es', _('Spanish')),
  ('en', _('English')),
)

LOCALE_PATHS = [
    '/srv/armatus/shared/app/locale/',
    os.path.join(BASE_DIR, 'locale/'),
]

TIME_ZONE = os.environ.get('TIME_ZONE')

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_CHARSET = 'utf-8'

LOGIN_URL = os.environ.get('LOGIN_URL')

LOGIN_REDIRECT_URL = os.environ.get('LOGIN_REDIRECT_URL')

STATIC_ROOT = os.environ.get('STATIC_ROOT')
STATIC_URL = os.environ.get('STATIC_URL')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# django configuration
SUIT_CONFIG = {
    'ADMIN_NAME': APPLICATION_NAME
}

SESSION_COOKIE_NAME = os.environ.get('SESSION_COOKIE_NAME')
SESSION_COOKIE_PATH = "/"


# =================================\
# ldap configuration
LDAP_SERVER = os.environ.get('LDAP_SERVER')
LDAP_DN = os.environ.get('LDAP_BIND_DN')

# =================================/

# =================================\
# FUEL_CONSUMPTION_COEFFICIENT = h/c
# h = hours performed by tank capacity
# c = indicates the size of the tank (coefficient between 0 and 1)
# ej: 1/4 tank every 10hs => FUEL_CONSUMPTION_COEFFICIENT = 10/0.25 = 40
FUEL_CONSUMPTION_COEFFICIENT = 40

#
# Being the range of the tank [0-1], the threshold indicates the value
# from which it is considered warning or danger
# ex. THRESHOLD_WARNING_TANK = 0.3
#     THRESHOLD_DANGER_TANK  = 0.1
# then the range is:
#       [0,   0.1]   danger
#       [0.1, 0.3]   warning
#       [0.   3.1]   normal
THRESHOLD_WARNING_TANK = 0.3
THRESHOLD_DANGER_TANK = 0.1
#
# Number of days remaining for the next services considered as danger or warning
THRESHOLD_WARNING_SERVICE = 10
THRESHOLD_DANGER_SERVICE = 5

# =================================/

# =================================\
# django ldap configuration
#
#
# Ldap Group Type
from django_auth_ldap.config import LDAPSearch, PosixGroupType
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(os.environ.get('LDAP_DN_AUTH_GROUP'),
                                    ldap.SCOPE_SUBTREE, "(objectClass=posixGroup)"
)
AUTH_LDAP_GROUP_TYPE =  PosixGroupType()
#
#
# User will be updated with LDAP every time the user logs in.
# Otherwise, the User will only be populated when it is automatically created.
AUTH_LDAP_ALWAYS_UPDATE_USER = True
#
#
# Simple group restrictions
# AUTH_LDAP_REQUIRE_GROUP = "cn=users,ou={},{}".format(LDAP_GROUP,LDAP_DN)
# AUTH_LDAP_DENY_GROUP = "cn=denygroup,ou={},{}".format(LDAP_GROUP,LDAP_DN)
#
# Defines the django admin attribute
# according to whether the user is a member or not in the specified group
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=users,{}".format(os.environ.get('LDAP_DN_AUTH_GROUP')),
    "is_staff": "cn=users,{}".format(os.environ.get('LDAP_DN_AUTH_GROUP')),
    "is_superuser": "cn=admin,{}".format(os.environ.get('LDAP_DN_AUTH_GROUP')),
}

#
# Ldap User Auth
#AUTH_LDAP_BIND_DN = "cn={},{}".format(LDAP_USERNAME,LDAP_DN)
#AUTH_LDAP_BIND_PASSWORD = LDAP_PASSWORD

AUTH_LDAP_SERVER_URI = os.environ.get('LDAP_SERVER')

AUTH_LDAP_USER_SEARCH = LDAPSearch(os.environ.get('LDAP_DN_AUTH_USERS'),
                                   ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # must be first to register
    'django_auth_ldap.backend.LDAPBackend', 
)


# =================================/
